// 定义action使用的常量
export const ADD_TAG = 'ADD_TAG';
export const SWITCH_THEME = 'SWITCH_THEME';
export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE';
export const SWITCH_COLLAPSE = 'SWITCH_COLLAPSE';
export const SWITCH_BASICDRAWER = 'SWITCH_BASICDRAWER';
export const SET_FULLSCREEN = 'SET_FULLSCREEN';
